[package]
name = "city-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy_rapier3d = "0.22.0"
image = "0.24.7"
smooth-bevy-cameras = "0.9.0"
